name: Sample MobSf Deployment 

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to github pages
        run: |
          sudo apt install nodejs
          sudo node --version
          sudo npm --version
          